### ISSUE TITLE
Chainmerklebranch always null

### ISSUE THREAD

**Issue by phelixbtc** [namecoin/namecore#22]
>$ getblock ac9237ab66fb0d605f9b67497dd66832fecaba968f0d862caff63e6c02e1f9df
> ...
>"chainmerklebranch": null,

Does it work for others? It did for me with the old client / a previous version of Namecoin core (can't recall which it was).

**Comment by phelixbtc** [comment]
It works for domob.
@JeremyRand @cassiniNMC   could you check whether you can get a proper "chainmerklebranch" for any block?

**Comment by JeremyRand** [comment]
I'm actually having trouble building the latest Namecoin Core code, so I can't try to reproduce on the current code.  I'll try to clean up my dev environment and see if I can get it to build -- might take a little while though.

**Comment by cassiniNMC** [comment]
Same here:
```getblock ac9237ab66fb0d605f9b67497dd66832fecaba968f0d862caff63e6c02e1f9df```
```
"chainmerklebranch": null,
```

Set the verbose flag to false and you get the data you are looking for:
```getblock ac9237ab66fb0d605f9b67497dd66832fecaba968f0d862caff63e6c02e1f9df false```
```
...
0200000000000000000000000000000000000000000000000000000000000000c2c25db0c08244d3eba88658a8fdfa01ecf1a5d52c5e787bcd95af626e02bfc2
...

**Comment by phelixbtc** [comment]
@cassiniNMC thanks for investigating and your hint that the data is there in the raw block.

Something seems to go wrong with clearing the UniValue as things work just fine if I create a second UniValue variable (e.g. branch2) to store the chainMerkleBranch.

**Comment by domob1812** [comment]
Hm, UniValue is a good hint.  I'll try to reproduce the issue again, maybe it was only recently introduced (with the change to UniValue).  In that case, it should be easy to fix and I'll try to work on it.

**Comment by domob1812** [comment]
With a very current daemon, I can indeed reproduce the issue.  Sorry for not trying that out earlier!  I'll work on a patch immediately.

**Comment by domob1812** [comment]
Fix pushed to master: https://github.com/namecoin/namecore/commit/97f520a33111e5ec69175fe547069503fa8dcac1

**Comment by phelixbtc** [comment]
:)
